var myjson = [
	{
		"HolidayReference": "1",
		"HotelName": "Uptown",
		"Area": "Bali",
		"Continent": "Asia",
		"Country": "Indonesia",
		"Category": "active/lazy",
		"StarRating": "3",
		"TempRating": "hot",
		"Location": "mountain",
		"PricePerPerNight": "100"
	},
	{
		"HolidayReference": "2",
		"HotelName": "Relaxamax",
		"Area": "New Orleans",
		"Continent": "North America",
		"Country": "USA",
		"Category": "lazy",
		"StarRating": "4",
		"TempRating": "mild",
		"Location": "city",
		"PricePerPerNight": "28"
	},
	{
		"HolidayReference": "3",
		"HotelName": "WindyBeach",
		"Area": "Ventry",
		"Continent": "Europe",
		"Country": "Ireland",
		"Category": "active",
		"StarRating": "3",
		"TempRating": "cold",
		"Location": "sea",
		"PricePerPerNight": "42"
	},
	{
		"HolidayReference": "4",
		"HotelName": "Twighlight",
		"Area": "Marrakech",
		"Continent": "Africa",
		"Country": "Morocco",
		"Category": "lazy",
		"StarRating": "5",
		"TempRating": "hot",
		"Location": "mountain",
		"PricePerPerNight": "50"
	},
	{
		"HolidayReference": "5",
		"HotelName": "TooHot",
		"Area": "Sydney",
		"Continent": "Australia",
		"Country": "Australia",
		"Category": "active/lazy",
		"StarRating": "5",
		"TempRating": "hot",
		"Location": "city",
		"PricePerPerNight": "67"
	},
	{
		"HolidayReference": "6",
		"HotelName": "Castaway",
		"Area": "Zanzibar",
		"Continent": "Africa",
		"Country": "Africa",
		"Category": "lazy",
		"StarRating": "3",
		"TempRating": "hot",
		"Location": "sea",
		"PricePerPerNight": "120"
	},
	{
		"HolidayReference": "7",
		"HotelName": "Eiffel Park",
		"Area": "Paris",
		"Continent": "Europe",
		"Country": "France",
		"Category": "active",
		"StarRating": "4",
		"TempRating": "mild",
		"Location": "city",
		"PricePerPerNight": "45"
	},
	{
		"HolidayReference": "8",
		"HotelName": "The Cape",
		"Area": "Cape Town",
		"Continent": "Africa",
		"Country": "South Africa",
		"Category": "active",
		"StarRating": "4",
		"TempRating": "hot",
		"Location": "sea",
		"PricePerPerNight": "78"
	},
	{
		"HolidayReference": "9",
		"HotelName": "Desert Dreams",
		"Area": "Dubai",
		"Continent": "Asia",
		"Country": "U.A.E",
		"Category": "active",
		"StarRating": "4",
		"TempRating": "hot",
		"Location": "city",
		"PricePerPerNight": "67"
	},
	{
		"HolidayReference": "10",
		"HotelName": "SeaViews",
		"Area": "Perth",
		"Continent": "Australia",
		"Country": "Australia",
		"Category": "active",
		"StarRating": "4",
		"TempRating": "hot",
		"Location": "sea",
		"PricePerPerNight": "80"
	},
	{
		"HolidayReference": "11",
		"HotelName": "AppleCity",
		"Area": "New York",
		"Continent": "North America",
		"Country": "USA",
		"Category": "active",
		"StarRating": "3",
		"TempRating": "mild",
		"Location": "city",
		"PricePerPerNight": "27"
	},
	{
		"HolidayReference": "12",
		"HotelName": "IslandHopper",
		"Area": "Dubrovnik",
		"Continent": "Europe",
		"Country": "Croatia",
		"Category": "active",
		"StarRating": "5",
		"TempRating": "mild",
		"Location": "sea",
		"PricePerPerNight": "78"
	},
	{
		"HolidayReference": "13",
		"HotelName": "CastleTown",
		"Area": "Edinburgh",
		"Continent": "Europe",
		"Country": "Scotland",
		"Category": "active",
		"StarRating": "3",
		"TempRating": "cold",
		"Location": "city",
		"PricePerPerNight": "53"
	},
	{
		"HolidayReference": "14",
		"HotelName": "WineValley",
		"Area": "Rome",
		"Continent": "Europe",
		"Country": "Italy",
		"Category": "lazy",
		"StarRating": "5",
		"TempRating": "mild",
		"Location": "city",
		"PricePerPerNight": "25"
	},
	{
		"HolidayReference": "15",
		"HotelName": "WearyTraveller",
		"Area": "Paro Valley",
		"Continent": "Asia",
		"Country": "Bhutan",
		"Category": "active",
		"StarRating": "5",
		"TempRating": "mild",
		"Location": "mountain",
		"PricePerPerNight": "54"
	},
	{
		"HolidayReference": "16",
		"HotelName": "HotTimes",
		"Area": "Jaipur",
		"Continent": "Asia",
		"Country": "India",
		"Category": "lazy",
		"StarRating": "4",
		"TempRating": "hot",
		"Location": "sea",
		"PricePerPerNight": "67"
	},
	{
		"HolidayReference": "17",
		"HotelName": "ForestRetreat",
		"Area": "Waikato",
		"Continent": "Australia",
		"Country": "New Zealand",
		"Category": "active",
		"StarRating": "4",
		"TempRating": "mild",
		"Location": "mountain",
		"PricePerPerNight": "89"
	},
	{
		"HolidayReference": "18",
		"HotelName": "Casablanca",
		"Area": "Havana",
		"Continent": "North America",
		"Country": "Cuba",
		"Category": "lazy",
		"StarRating": "5",
		"TempRating": "hot/mild",
		"Location": "city",
		"PricePerPerNight": "29"
	},
	{
		"HolidayReference": "19",
		"HotelName": "TechCity",
		"Area": "Tokyo",
		"Continent": "Asia",
		"Country": "Japan",
		"Category": "active",
		"StarRating": "3",
		"TempRating": "mild",
		"Location": "city",
		"PricePerPerNight": "71"
	},
	{
		"HolidayReference": "20",
		"HotelName": "IceHotel",
		"Area": "Base Marambio",
		"Continent": "Antarctica",
		"Country": "Antartica",
		"Category": "active",
		"StarRating": "5",
		"TempRating": "cold",
		"Location": "mountain",
		"PricePerPerNight": "270"
	},
	{
		"HolidayReference": "21",
		"HotelName": "NorthStar",
		"Area": "Saattut",
		"Continent": "Arctic",
		"Country": "Greenland",
		"Category": "active",
		"StarRating": "5",
		"TempRating": "cold",
		"Location": "mountain",
		"PricePerPerNight": "250"
	},
	{
		"HolidayReference": "22",
		"HotelName": "Forest cabin",
		"Area": "Geilo",
		"Continent": "Europe",
		"Country": "Norway",
		"Category": "active",
		"StarRating": "5",
		"TempRating": "cold",
		"Location": "mountain",
		"PricePerPerNight": "250"
	},
	{
		"HolidayReference": "23",
		"HotelName": "Tralala hotel montreux",
		"Area": "Montreux",
		"Continent": "Europe",
		"Country": "Switzerland",
		"Category": "active",
		"StarRating": "4",
		"TempRating": "cold",
		"Location": "mountain",
		"PricePerPerNight": "170"
	},
	{
		"HolidayReference": "24",
		"HotelName": "Hotel Etna",
		"Area": "Sicily",
		"Continent": "Europe",
		"Country": "Italy",
		"Category": "active",
		"StarRating": "4",
		"TempRating": "hot",
		"Location": "mountain",
		"PricePerPerNight": "120"
	},
	{
		"HolidayReference": "25",
		"HotelName": "Wild pheasant hotel",
		"Area": "Wales",
		"Continent": "Europe",
		"Country": "UK",
		"Category": "active",
		"StarRating": "4",
		"TempRating": "cold",
		"Location": "mountain",
		"PricePerPerNight": "120"
	},
	{
		"HolidayReference": "26",
		"HotelName": "Rayrigg villa guest house",
		"Area": "Lake district",
		"Continent": "Europe",
		"Country": "UK",
		"Category": "active",
		"StarRating": "3",
		"TempRating": "cold",
		"Location": "lake",
		"PricePerPerNight": "150"
	},
	{
		"HolidayReference": "27",
		"HotelName": "The Devonshire fell hotel",
		"Area": "Yorkshire",
		"Continent": "Europe",
		"Country": "UK",
		"Category": "active",
		"StarRating": "4",
		"TempRating": "cold",
		"Location": "lake",
		"PricePerPerNight": "120"
	},
	{
		"HolidayReference": "28",
		"HotelName": "Atrium Palace spa resort",
		"Area": "Theotokos",
		"Continent": "Europe",
		"Country": "Greece",
		"Category": "lazy",
		"StarRating": "4",
		"TempRating": "hot",
		"Location": "sea",
		"PricePerPerNight": "75"
	},
	{
		"HolidayReference": "29",
		"HotelName": "Princess cruises",
		"Area": "Philippines",
		"Continent": "Asia",
		"Country": "Philippines",
		"Category": "lazy",
		"StarRating": "5",
		"TempRating": "hot",
		"Location": "cruise",
		"PricePerPerNight": "120"
	},
	{
		"HolidayReference": "30",
		"HotelName": "Diamond cruises",
		"Area": "Sydney",
		"Continent": "Australia",
		"Country": "Australia",
		"Category": "lazy",
		"StarRating": "5",
		"TempRating": "hot",
		"Location": "cruise",
		"PricePerPerNight": "180"
	},
	{
		"HolidayReference": ""
	}
]

export {myjson};

